version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: portal_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - portal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    networks:
      - default
      - compras_net
      - pagamentos_net
      - faturacao_net
      - kpi_analytics_net
      - importacao_net
      - guiaderemessa_net
    restart: always

  portal:
    build: ./portal
    container_name: portal_backend
    volumes:
      - ./portal/data:/usr/src/app/data
    environment:
      - PORT=3000
      - COOKIE_SECRET=super-secure-portal-key-13579
    networks:
      - default
    restart: always

volumes:
  certbot-etc:
  certbot-var:
  webroot:

networks:
  default:
  compras_net:
    external: true
    name: pedidodecompradematerial_default
  pagamentos_net:
    external: true
    name: pedidodepagamento_default
  faturacao_net:
    external: true
    name: facturacaodeservicos_default
  kpi_analytics_net:
    external: true
    name: workflowkpianalytics_default
  importacao_net:
    external: true
    name: processodeimportacao_default
  guiaderemessa_net:
    external: true
    name: guiaderemessa-network
